FROM cbmc-binaries AS cbmc

FROM viewer-binaries AS viewer

FROM ubuntu:20.04

ENV CBMC_SOURCE=/tmp/cbmc-source
ENV CBMC_STAGING=/tmp/cbmc-staging
ENV CBMC_INSTALL=/

ENV VIEWER_SOURCE=/tmp/viewer-source
ENV VIEWER_STAGING=/tmp/viewer-staging
ENV VIEWER_INSTALL=/usr/local/cbmc-viewer

ENV PATH="/usr/local/bin:/usr/local/cbmc-viewer:${PATH}"

ENV PS1="cbmc:\w "
RUN echo PS1=\"${PS1}\" >> /root/.bashrc

COPY --from=cbmc ${CBMC_STAGING} ${CBMC_STAGING}
COPY --from=viewer ${VIEWER_STAGING} ${VIEWER_STAGING}

# install build dependencies
RUN \
  apt update && apt install -y \
    ctags \
    gcc \
    git \
    libc6-dev-i386 \
    ninja-build \
    python-is-python3 \
    python3 \
    python3-pip
RUN python3 -m pip install voluptuous jinja2

RUN \
  mkdir -p ${CBMC_INSTALL} && \
  cp -R ${CBMC_STAGING}/* ${CBMC_INSTALL} && \
  rm -rf ${CBMC_STAGING} && \
  mkdir -p ${VIEWER_INSTALL} && \
  cp -R ${VIEWER_STAGING}/* ${VIEWER_INSTALL} && \
  rm -rf ${VIEWER_STAGING}
