Description: >
  Enable storage of access tokens in AWS Secrets Manager and access to the PAT
  from the GitHub workflows in model-checking/cbmc-viewer.

Parameters:
  GithubRepoOrganization:
    Type: String
    Description: GitHub organization for the CBMC viewer
    Default: model-checking
  CbmcViewerRepoName:
    Type: String
    Description: GitHub repository for CBMC viewer
    Default: cbmc-viewer
  CbmcViewerPublicationTag:
    Type: String
    Description: GitHub tag for CBMC viewer triggering the GitHub publication workflow
    Default: viewer-*

Resources:

  BrewBotEmail:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: BOT_EMAIL
      Description: >
        The email address to use with Homebrew commits.

  BrewToken:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: RELEASE_CI_ACCESS_TOKEN
      Description: >
        GitHub access token.

  PypiToken:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: PYPI_ACCESS_TOKEN
      Description: >
        Pypi access token.

  PublisherTokenReader:
    Type: AWS::IAM::Role
    Properties:
      RoleName: PublisherTokenReader
      Description: >
        This role can retrieve the personal access token for the model
        checking publisher in the Microsoft Marketplace.

      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Federated: !ImportValue GithubIdentityProvider
            Action: sts:AssumeRoleWithWebIdentity
            Condition:
              StringEquals:
                token.actions.githubusercontent.com:aud: sts.amazonaws.com
              StringLike:
                token.actions.githubusercontent.com:sub:
                  !Sub repo:${GithubRepoOrganization}/${CbmcViewerRepoName}:ref:refs/tags/${CbmcViewerPublicationTag}

      Policies:
        - PolicyName: PublisherTokenAccess
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action: secretsmanager:GetSecretValue
                Resource: !Ref BrewBotEmail
              - Effect: Allow
                Action: secretsmanager:GetSecretValue
                Resource: !Ref BrewToken
              - Effect: Allow
                Action: secretsmanager:GetSecretValue
                Resource: !Ref PypiToken
